{% set version = "1.6.0" %}

package:
  name: pyflakes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyflakes/pyflakes-{{ version }}.tar.gz
  sha256: 8d616a382f243dbf19b54743f280b80198be0bca3a5396f1d2e1fca6223e8805

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyflakes

about:
  home: https://github.com/PyCQA/pyflakes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pyflakes analyzes programs and detects various errors.'
  dev_url: https://github.com/PyCQA/pyflakes

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
